zuul:
  routes:
    get:
      path: /hi/**
      url: https://dd-docker-demo.herokuapp.com/hi
    links:
      path: /links/**
      url: http://httpbin.org/links
    images:
      path: /image/**
      url: http://httpbin.org/image

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:5000}/eureka/